### ISSUE TITLE
WebInterface should check for correct return type

### ISSUE THREAD

**Issue by eguven** [deliveryhero/lymph#287]
lymph fails when setting trace-id header in case the return type from WebInterface is not correct type. lymph should probably check for this and raise before.

    Traceback (most recent call last):
      File "/home/eren.gueven/.virtualenvs/ars/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
        self.run_application()
      File "/home/eren.gueven/.virtualenvs/ars/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
        self.result = self.application(self.environ, self.start_response)
      File "/home/eren.gueven/.virtualenvs/ars/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 291, in application
        return f(*args[:-2] + (request,))(*args[-2:])
      File "/home/eren.gueven/.virtualenvs/ars/local/lib/python2.7/site-packages/lymph/web/interfaces.py", line 114, in dispatch_request
        response.headers['X-Trace-Id'] = trace.get_id()
    AttributeError: 'NoneType' object has no attribute 'headers'

**Comment by emulbreh** [comment]
Fixed in #288
